Algoritmo "Repita Exemplo"
// Disciplina   : [Lógica de Programação]
// Professor   :Jailson 
// Descrição   : Exemplo de repetição
// Autor(a)    : Vinicius Mendes da Silva
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
Escreval("Vinicius")
contadora<-contadora+1
ate contadora>=10


Fimalgoritmo