Algoritmo "Repita caio"
// Disciplina   : [Lógica de Programação]
// Professor   :Jailson
// Descrição   : Exemplo de repetição
// Autor(a)    : Vinicius Mendes da Silva
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis
contadora,numeropar:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
repita
contadora<-contadora + 1
se contador mod 2 = 0 entao
numeropar<- numeropar+contadora
fimse
ate contadora>=500

escreval(numeropar)


Fimalgoritmo