Algoritmo "7C Volume Lata óleo"
// Disciplina   : [Lógica de Programação]
// Professor   :Jailson 
// Descrição   : calcula o volume de uma lata de óleo
// Autor(a)    : Vinicius Mendes da Silva
// Data atual  : 13/09/2024
Var
// Seção de Declarações das variáveis 
volume,raio,altura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
raio<- 4.5
altura<-10
Volume <- pi*raio*altura

Escreval("O Volume da altura é: ",Volume)
Fimalgoritmo